# -*- coding: utf-8 -*-
#
# This file is part of hepcrawl.
# Copyright (C) 2017 CERN.
#
# hepcrawl is a free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see LICENSE file for
# more details.

version: '2.1'

services:
  service_base: &service_base
    image: hepcrawl_base  # hepcrawl_base image is build at pip service of docker-compose.deps.yml
    environment:
      - APP_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - APP_CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
      - APP_CRAWLER_HOST_URL=http://scrapyd:6800
      - APP_API_PIPELINE_TASK_ENDPOINT_DEFAULT=hepcrawl.testlib.tasks.submit_results
      - APP_FILES_STORE=/tmp/file_urls
      - APP_CRAWL_ONCE_PATH=/var/lib/scrapy/crawl_once/
      - COVERAGE_PROCESS_START=/code/.coveragerc
      - BASE_USER_UID=${BASE_USER_UID:-1000}
      - BASE_USER_GIT=${BASE_USER_GIT:-1000}
    tty: true
    volumes:
      - ${DOCKER_DATA}/tmp/hepcrawl_venv:/hepcrawl_venv/
      - ${PWD}:/code/
      - ${PWD}/tests/functional/scrapyd_coverage_runner.conf:/etc/scrapyd/scrapyd.conf
      - /tmp/WSP:/tmp/WSP
      - /tmp/file_urls:/tmp/file_urls
      - ${PWD}/.scrapy/crawl_once:/var/lib/scrapy/crawl_once

  functional_wsp:
    <<: *service_base
    command: py.test -vv tests/functional/wsp
    links:
      - scrapyd
      - ftp_server

  functional_desy:
    <<: *service_base
    command: py.test -vv tests/functional/desy
    links:
      - scrapyd
      - ftp_server

  functional_arxiv:
    <<: *service_base
    command: py.test -vv tests/functional/arxiv
    links:
      - scrapyd

  unit:
    <<: *service_base
    command: bash -c "py.test tests/unit -vv && make -C docs clean && make -C docs html && python setup.py sdist && ls dist/*"
    links: []

  celery:
    <<: *service_base
    command: celery worker --events --app hepcrawl.testlib.tasks --loglevel=debug
    links:
      - rabbitmq

  scrapyd:
    <<: *service_base
    command: bash -c "rm -f twistd.pid && exec scrapyd"
    links:
      - celery

  scrapyd_deploy:
    <<: *service_base
    command: bash -c "sleep 8 && scrapyd-deploy"  # make sure that the scrapyd is up
    links:
      - scrapyd

  ftp_server:
    image: stilliard/pure-ftpd:hardened
    environment:
      - PUBLICHOST=localhost
    volumes:
      - ${PWD}/tests/functional/desy/fixtures/ftp_server/FFT:/home/ftpusers/bob/FFT
      - ${PWD}/tests/functional/desy/fixtures/ftp_server/DESY:/home/ftpusers/bob/DESY
      - ${PWD}/tests/functional/wsp/fixtures/ftp_server/WSP:/home/ftpusers/bob/WSP
      - ${PWD}/tests/functional/wsp/fixtures/ftp_server/pureftpd.passwd:/etc/pure-ftpd/passwd/pureftpd.passwd

  rabbitmq:
    image: rabbitmq
